In [1]:
##Numpy- Numerical Python


In [2]:
data=[10,20,30,40,50,60]

In [3]:
type(data)

list

In [4]:
import numpy as np

In [5]:
arr=np.array(data)

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.random.randn(4,5)

array([[ 1.61362888e-01, -6.08576873e-01,  3.61668603e-01,
         7.88993253e-01,  1.92601603e+00],
       [-1.51405267e+00, -4.21470170e-01,  7.82931166e-01,
        -1.70562539e-01, -8.90425910e-01],
       [-3.57424781e-01, -5.45899193e-04, -9.75451292e-01,
        -7.06213290e-04, -2.23862778e+00],
       [-2.90983272e-01,  3.96060777e-01,  4.04574154e-01,
         4.44276629e-01,  3.11386363e-01]])

In [8]:
np.random.randint(1)

0

In [9]:
np.random.randint(2)

1

In [10]:
np.random.randint(5,20)

19

In [11]:
np.random.randint(5,20,6)

array([19, 16, 16, 13, 18, 19])

In [13]:
#generate number
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,100) #start,stop

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [16]:
np.arange(10,100,5) #start,stop,step

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [18]:
np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [20]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
np.arange(1,26).reshape(1,25)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [22]:
np.arange(1,26).reshape(25,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [23]:
arr=np.arange(1,26).reshape(5,5)

In [24]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
arr.shape

(5, 5)

In [26]:
arr.ndim  #dimentional of array

2

In [27]:
a1=np.arange(1,26)

In [28]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [29]:
a1.shape

(25,)

In [30]:
#zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.ones(5)*4  #got 5 four

array([4., 4., 4., 4., 4.])

In [38]:
np.ones(5)+4 #got 5 four

array([5., 5., 5., 5., 5.])

# Indentity Matrix

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
#another way 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.eye(4,5) #row column

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

# linspace() method

In [45]:
#generate data from linearly(equal) space
np.linspace(0,10,3)  #3=>give me linearly space ele between 1 and 10

array([ 0.,  5., 10.])

In [46]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [48]:
np.linspace(10,100,50)

array([ 10.        ,  11.83673469,  13.67346939,  15.51020408,
        17.34693878,  19.18367347,  21.02040816,  22.85714286,
        24.69387755,  26.53061224,  28.36734694,  30.20408163,
        32.04081633,  33.87755102,  35.71428571,  37.55102041,
        39.3877551 ,  41.2244898 ,  43.06122449,  44.89795918,
        46.73469388,  48.57142857,  50.40816327,  52.24489796,
        54.08163265,  55.91836735,  57.75510204,  59.59183673,
        61.42857143,  63.26530612,  65.10204082,  66.93877551,
        68.7755102 ,  70.6122449 ,  72.44897959,  74.28571429,
        76.12244898,  77.95918367,  79.79591837,  81.63265306,
        83.46938776,  85.30612245,  87.14285714,  88.97959184,
        90.81632653,  92.65306122,  94.48979592,  96.32653061,
        98.16326531, 100.        ])

In [49]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [50]:
arr=np.arange(1,26).reshape(5,5)

In [51]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
arr.shape

(5, 5)

In [53]:
arr[3,3]

19

In [56]:
arr[1:3,3:4]

array([[ 9],
       [14]])

In [59]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [61]:
arr[1:2,1:4]

array([[7, 8, 9]])

In [62]:
arr[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [63]:
arr[::1,4]

array([ 5, 10, 15, 20, 25])

In [64]:
arr[0:5,4:5]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [65]:
arr[:,4:5]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [66]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
arr[[0,3],[1,3]]

array([ 2, 19])

In [71]:
arr[[0,4],[4,0]]

array([ 5, 21])

In [74]:
np.arange(0.01, 1.01, 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [75]:
np.linspace(0.1,1,100).reshape(10,10)

array([[0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
        0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818],
       [0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
        0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727],
       [0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
        0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636],
       [0.37272727, 0.38181818, 0.39090909, 0.4       , 0.40909091,
        0.41818182, 0.42727273, 0.43636364, 0.44545455, 0.45454545],
       [0.46363636, 0.47272727, 0.48181818, 0.49090909, 0.5       ,
        0.50909091, 0.51818182, 0.52727273, 0.53636364, 0.54545455],
       [0.55454545, 0.56363636, 0.57272727, 0.58181818, 0.59090909,
        0.6       , 0.60909091, 0.61818182, 0.62727273, 0.63636364],
       [0.64545455, 0.65454545, 0.66363636, 0.67272727, 0.68181818,
        0.69090909, 0.7       , 0.70909091, 0.71818182, 0.72727273],
       [0.73636364, 0.74545455, 0.7545454

In [77]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
arr=np.zeros((10,10))
arr[1:]=1 
arr[2:]=2 
arr[3:]=3 
arr[4:]=4 
arr[5:]=5 
arr[6:]=6 
arr[7:]=7 
arr[8:]=8 
arr[9:]=9 
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [90]:
arr=np.zeros((10,10)) 
for i in range(10): 
    arr[i]+=i 
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

# numpy array support broadcasting


In [99]:
#Broadcasting==>subset change into original array
arr=np.arange(1,26)

In [92]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [95]:
arr_subset=arr[5:12]
arr_subset

array([ 6,  7,  8,  9, 10, 11, 12])

In [96]:
arr_subset[1:5]

array([ 7,  8,  9, 10])

In [97]:
arr_subset[1:5]=89

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6, 89, 89, 89, 89, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [100]:
arr_subset

array([ 6, 89, 89, 89, 89, 11, 12])

In [101]:
arr=np.arange(1,26)

In [102]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [103]:
arr_copy=arr.copy()

In [104]:
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [106]:
arr2d=arr.reshape(5,5)

In [107]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [108]:
arr2d.sum()

325

In [110]:
arr2d[:,:].sum()

325

In [111]:
arr2d.sum(axis=0)   #addition of every element 1st,2nd,3rd,4th

array([55, 60, 65, 70, 75])

In [112]:
arr2d.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [113]:
"7"+2

TypeError: can only concatenate str (not "int") to str